### ISSUE TITLE
Option to wait element hidden

### ISSUE THREAD

**Issue by BobCashStory** [1natsu172/wait-element#6]
i like your lib and help me a lot.
I would like to be able to wait for hidden too like there :
https://pptr.dev/#?product=Puppeteer&version=v5.2.1&show=api-pagewaitforselectorselector-options

does it look something intersting for you ?

**Comment by BobCashStory** [comment]
#7 is a PR related to this

**Comment by 1natsu172** [comment]
@BobCashStory Hi thanks issue & PR. I'm interested. If you're willing to submit a PR, can get the feature into the library.

#7 PR doesn't seem to be something that works yet. Please leave it as a draft PR once. Open it up when it's available for review again. When it's finished, open it up again.

**Comment by 1natsu172** [comment]
@BobCashStory New version v3 implements the same functionality. 

It is provided by a separate API called `waitDisappearElement`. 

Best regards.
